(cl:defpackage rasa_ros-srv
  (:use )
  (:export
   "DIALOGUE"
   "<DIALOGUE-REQUEST>"
   "DIALOGUE-REQUEST"
   "<DIALOGUE-RESPONSE>"
   "DIALOGUE-RESPONSE"
   "TEXT2SPEECH"
   "<TEXT2SPEECH-REQUEST>"
   "TEXT2SPEECH-REQUEST"
   "<TEXT2SPEECH-RESPONSE>"
   "TEXT2SPEECH-RESPONSE"
  ))

